# There are two types of forward simulation
# 1) forward simulation for source_inversion: for this
#     case, one event need to have 10 forward simulations,
#     one for original CMT, the other 9 for perturbed CMTs
#     keyword: "source_inversion"
# 2) forward_simulation for structral inversion: for
#     this case, one event only needs to have 1 forward simulation
#     keyword: "structure_inversion". However, for forward simulation
#     , you may want to save the DATABASES_MPI if you want to save the
#     forward wavefield
simulation_type: "structure_inversion"

job_info:
  # this branch only support simultaneous and serial runs, which means you use one mpirun to
  # excute multiple simulation at the same time, and serial run several simul runs
  running_mode: "simul_and_serial"
  # number of serial run on top of simul runs(number of simultaneous runs in serial)
  # only used in "simul_and_serial" mode
  nsimul_serial: 5
  # number of events in one job(with simultaneous run)
  nevents_per_simul_run: 5
  # walltime for one forward simulation(unit is minutes)
  walltime_per_simulation: 12

data_info:
  # CMT folder: directory where you store cmt files
  cmtfolder: "/ccs/home/lei/SOURCE_INVERSION/iter0/cmt_origin"

  # station folder
  # setting different station files for different simulations(sources)
  # station file should be named as: eventname.STATIONS
  # for example: C200501121652A.STATIONS
  stationfolder: "/ccs/home/lei/SOURCE_INVERSION/iter0/STATIONS"

  # RUNBASE: the runbase is the directory where holds all running files
  # So make sure that your runbase is large enough to hold everything
  runbase: "/lustre/atlas/proj-shared/geo111/Wenjie/test/seisforward/runbase"

  # The large eventfile you want to split
  total_eventfile: "XEVENTID.missing_lat"

  # job sub-folder tag
  job_tag: "si_test"

  # the direcotry of specfem3d_globe
  specfemdir: "/lustre/atlas/proj-shared/geo111/Wenjie/bm_specfem/test/specfem3d_globe_ASDF_adj"

srcinv_info:
  # Setup for source_inversion(Not used if structure_inversion)
  # Generate derivative CMTSOLUTION file
  # If false, then you need to generate the derivative CMT
  # externally(put them the same directory same as "cmtfolder")
  # and then they will be copied in the job directory;
  # If true, the derivative CMT will be generated internally.
  generate_deriv_cmt: true
  # Derive CMT list
  # For example: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
  deriv_cmt_list: ["Mrr", "Mtt", "Mpp", "Mrt", "Mrp", "Mtp", "dep", "lon", "lat"]
  # CMT perturbation
  # Not used if "generate_deriv_cmt" is false
  dmoment_tensor: 2.0e+23  # dyne * cm
  ddepth: 3.0        # km
  dlatitude: 0.03   # degree
  dlongitude: 0.03   # degree
